using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NewSmiteToolkit.Constants
{
    public static class SmiteFireGods
    {
        public static Dictionary<string, int> Ids = new Dictionary<string, int>
        {
            {"Achilles", 94},
            {"Agni", 18},
            {"Ah Muzen Cab", 45},
            {"Ah Puch", 65},
            {"Amaterasu", 72},
            {"Anhur", 5},
            {"Anubis", 6},
            {"Ao Kuang", 60},
            {"Aphrodite", 32},
            {"Apollo", 33},
            {"Arachne", 2},
            {"Ares", 23},
            {"Artemis", 1},
            {"Artio", 90},
            {"Athena", 37},
            {"Awilix", 61},
            {"Baba Yaga", 109},
            {"Bacchus", 26},
            {"Bakasura", 19},
            {"Baron Samedi", 96},
            {"Bastet", 7},
            {"Bellona", 63},
            {"Cabrakan", 57},
            {"Camazotz", 81},
            {"Cerberus", 93},
            {"Cernunnos", 86},
            {"Chaac", 47},
            {"Chang'e", 40},
            {"Chernobog", 95},
            {"Chiron", 71},
            {"Chronos", 39},
            {"Cthulhu", 110},
            {"Cu Chulainn", 89},
            {"Cupid", 17},
            {"Da Ji", 88},
            {"Danzaburou", 112},
            {"Discordia", 92},
            {"Erlang Shen", 78},
            {"Eset", 36},
            {"Fafnir", 77},
            {"Fenrir", 35},
            {"Freya", 24},
            {"Ganesha", 87},
            {"Geb", 48},
            {"Gilgamesh", 114},
            {"Guan Yu", 14},
            {"Hachiman", 91},
            {"Hades", 3},
            {"He Bo", 15},
            {"Heimdallr", 107},
            {"Hel", 10},
            {"Hera", 98},
            {"Hercules", 28},
            {"Horus", 103},
            {"Hou Yi", 62},
            {"Hun Batz", 38},
            {"Izanami", 80},
            {"Janus", 54},
            {"Jing Wei", 75},
            {"Jormungandr", 101},
            {"Kali", 20},
            {"Khepri", 68},
            {"King Arthur", 99},
            {"Kukulkan", 13},
            {"Kumbhakarna", 52},
            {"Kuzenbo", 85},
            {"Loki", 25},
            {"Medusa", 64},
            {"Mercury", 44},
            {"Merlin", 100},
            {"Mulan", 108},
            {"Ne Zha", 34},
            {"Neith", 30},
            {"Nemesis", 49},
            {"Nike", 83},
            {"Nox", 59},
            {"Nu Wa", 46},
            {"Odin", 11},
            {"Olorun", 104},
            {"Osiris", 53},
            {"Pele", 97},
            {"Persephone", 105},
            {"Poseidon", 31},
            {"Ra", 8},
            {"Raijin", 73},
            {"Rama", 55},
            {"Ratatoskr", 66},
            {"Ravana", 67},
            {"Scylla", 50},
            {"Serqet", 56},
            {"Set", 102},
            {"Skadi", 74},
            {"Sobek", 9},
            {"Sol", 70},
            {"Sun Wukong", 16},
            {"Susano", 76},
            {"Sylvanus", 58},
            {"Terra", 79},
            {"Thanatos", 43},
            {"The Morrigan", 84},
            {"Thor", 22},
            {"Thoth", 82},
            {"Tiamat", 113},
            {"Tsukuyomi", 111},
            {"Tyr", 41},
            {"Ullr", 51},
            {"Vamana", 21},
            {"Vulcan", 29},
            {"Xbalanque", 27},
            {"Xing Tian", 69},
            {"Yemoja", 106},
            {"Ymir", 12},
            {"Zeus", 4},
            {"Zhong Kui", 4},
        };
    }
}